#!/usr/bin/env bash
# Patches the canonical Orbit identifiers ("com.orbit.app" /
# "group.com.orbit.app") to your personal IDs across project.yml,
# entitlements, and Swift literals. Stores your IDs in a gitignored
# Config/Identity.xcconfig so subsequent runs (after a git pull that
# touches project.yml) can re-apply without arguments.
#
# First-time usage:
#
#   ./Scripts/setup-identity.sh com.joshgreen.orbit group.com.joshgreen.orbit
#
# Subsequent runs (after `git pull` resurfaces the canonical IDs):
#
#   ./Scripts/setup-identity.sh        # reads from Config/Identity.xcconfig
#
# After running, regenerate Xcode:
#
#   xcodegen generate

set -euo pipefail

CANONICAL_BUNDLE="com.orbit.app"
CANONICAL_GROUP="group.com.orbit.app"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
IDENTITY_FILE="$REPO_ROOT/Config/Identity.xcconfig"

# Resolve target identifiers.
if [ "$#" -eq 2 ]; then
    NEW_BUNDLE="$1"
    NEW_GROUP="$2"
elif [ "$#" -eq 0 ] && [ -f "$IDENTITY_FILE" ]; then
    NEW_BUNDLE="$(grep -E '^ORBIT_BUNDLE_ID' "$IDENTITY_FILE" | head -1 | sed 's/.*=//; s/^ *//; s/ *$//')"
    NEW_GROUP="$(grep -E '^ORBIT_APP_GROUP' "$IDENTITY_FILE" | head -1 | sed 's/.*=//; s/^ *//; s/ *$//')"
    if [ -z "$NEW_BUNDLE" ] || [ -z "$NEW_GROUP" ]; then
        echo "Error: $IDENTITY_FILE exists but couldn't parse ORBIT_BUNDLE_ID / ORBIT_APP_GROUP." >&2
        exit 1
    fi
    echo "Re-applying identity from $IDENTITY_FILE:"
    echo "  ORBIT_BUNDLE_ID = $NEW_BUNDLE"
    echo "  ORBIT_APP_GROUP = $NEW_GROUP"
else
    cat >&2 <<USAGE
Usage:
  $0 <bundle-id> <app-group-id>          first-time setup
  $0                                      re-apply from Config/Identity.xcconfig

Examples:
  $0 com.joshgreen.orbit group.com.joshgreen.orbit
USAGE
    exit 1
fi

if [[ "$NEW_GROUP" != group.* ]]; then
    echo "Error: App Group identifier must start with 'group.'" >&2
    exit 1
fi

cd "$REPO_ROOT"

# Files that contain the canonical identifiers and need to be patched.
TARGETS=(
    "project.yml"
    "App/Resources/Orbit.entitlements"
    "Extensions/ShareExtension/Orbit.entitlements"
    "Extensions/OrbitWidgets/Orbit.entitlements"
    "Extensions/ShareExtension/ShareViewController.swift"
    "Extensions/OrbitWidgets/RecentMemoryWidget.swift"
    "Packages/OrbitKit/Sources/OrbitKit/AppConfig.swift"
)

for file in "${TARGETS[@]}"; do
    if [ ! -f "$file" ]; then
        echo "Skipping (not found): $file"
        continue
    fi
    # Order matters: group ID first because it contains the bundle ID as a
    # prefix (otherwise the bundle replace would corrupt group.com.orbit.app).
    perl -i -pe "s/\Q$CANONICAL_GROUP\E/$NEW_GROUP/g" "$file"
    perl -i -pe "s/\Q$CANONICAL_BUNDLE\E/$NEW_BUNDLE/g" "$file"
    echo "Patched: $file"
done

# Record current identifiers so the script can re-apply itself after a
# pull resurfaces the canonical strings.
mkdir -p Config
cat > "$IDENTITY_FILE" <<EOF
// Identity.xcconfig — personal identifiers for this machine.
// Generated by Scripts/setup-identity.sh on $(date "+%Y-%m-%d %H:%M:%S").
// Gitignored: see .gitignore. Re-run ./Scripts/setup-identity.sh after
// any \`git pull\` that touches project.yml.

ORBIT_BUNDLE_ID = $NEW_BUNDLE
ORBIT_APP_GROUP = $NEW_GROUP
EOF

echo ""
echo "Wrote $IDENTITY_FILE."
echo ""
echo "Next: xcodegen generate"
