#!/usr/bin/env bash
# Patches the canonical Orbit identifiers ("com.orbit.app" /
# "group.com.orbit.app") to your personal IDs across project.yml,
# entitlements, and Swift literals. Stores your IDs — plus your Apple
# developer team ID — in a gitignored Config/Identity.xcconfig so
# `xcodegen generate` never wipes signing settings between runs.
#
# First-time usage:
#
#   ./Scripts/setup-identity.sh com.joshgreen.orbit group.com.joshgreen.orbit ABCD123456
#
# The team ID is the 10-char string Apple assigns you. Find it in:
#   Xcode → Settings → Accounts → (your Apple ID) → Team → Team ID column
# or:
#   https://developer.apple.com/account → Membership → Team ID
#
# Subsequent runs (after `git pull` resurfaces the canonical IDs):
#
#   ./Scripts/setup-identity.sh        # reads everything from Identity.xcconfig
#
# After running, regenerate Xcode:
#
#   xcodegen generate

set -euo pipefail

CANONICAL_BUNDLE="com.orbit.app"
CANONICAL_GROUP="group.com.orbit.app"
TEAM_PLACEHOLDER="ORBIT_TEAM_ID_PLACEHOLDER"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
IDENTITY_FILE="$REPO_ROOT/Config/Identity.xcconfig"

# Read an existing value (if any) before we overwrite the file. Used so a
# 2-arg invocation preserves a previously-written DEVELOPMENT_TEAM, and so
# a 0-arg invocation can pull everything out together.
#
# `|| true` keeps `set -e` from aborting when the key isn't present in the
# file — grep exits 1 on no match, pipefail propagates it, and the whole
# script would otherwise die silently before doing any work.
read_identity_value() {
    local key="$1"
    [ -f "$IDENTITY_FILE" ] || { echo ""; return; }
    grep -E "^${key}" "$IDENTITY_FILE" 2>/dev/null | head -1 | sed 's/.*=//; s/^ *//; s/ *$//' || true
}

NEW_TEAM="$(read_identity_value DEVELOPMENT_TEAM)"

# Resolve target identifiers.
if [ "$#" -ge 2 ]; then
    NEW_BUNDLE="$1"
    NEW_GROUP="$2"
    if [ "$#" -ge 3 ]; then
        NEW_TEAM="$3"
    fi
elif [ "$#" -eq 0 ] && [ -f "$IDENTITY_FILE" ]; then
    NEW_BUNDLE="$(read_identity_value ORBIT_BUNDLE_ID)"
    NEW_GROUP="$(read_identity_value ORBIT_APP_GROUP)"
    if [ -z "$NEW_BUNDLE" ] || [ -z "$NEW_GROUP" ]; then
        echo "Error: $IDENTITY_FILE exists but couldn't parse ORBIT_BUNDLE_ID / ORBIT_APP_GROUP." >&2
        exit 1
    fi
    echo "Re-applying identity from $IDENTITY_FILE:"
    echo "  ORBIT_BUNDLE_ID  = $NEW_BUNDLE"
    echo "  ORBIT_APP_GROUP  = $NEW_GROUP"
    if [ -n "$NEW_TEAM" ]; then
        echo "  DEVELOPMENT_TEAM = $NEW_TEAM"
    fi
else
    cat >&2 <<USAGE
Usage:
  $0 <bundle-id> <app-group-id> [team-id]    first-time setup
  $0                                          re-apply from Config/Identity.xcconfig

Examples:
  $0 com.joshgreen.orbit group.com.joshgreen.orbit ABCD123456
USAGE
    exit 1
fi

if [[ "$NEW_GROUP" != group.* ]]; then
    echo "Error: App Group identifier must start with 'group.'" >&2
    exit 1
fi

cd "$REPO_ROOT"

# Files that contain the canonical identifiers and need to be patched.
TARGETS=(
    "project.yml"
    "App/Resources/Orbit.entitlements"
    "Extensions/ShareExtension/Orbit.entitlements"
    "Extensions/OrbitWidgets/Orbit.entitlements"
    "Extensions/CameraCapture/Orbit.entitlements"
    "Extensions/SafariExtension/Orbit.entitlements"
    "Extensions/ShareExtension/ShareViewController.swift"
    "Extensions/OrbitWidgets/RecentMemoryWidget.swift"
    "Extensions/SafariExtension/SafariWebExtensionHandler.swift"
    "Extensions/SafariExtension/Resources/background.js"
    "Packages/OrbitKit/Sources/OrbitKit/AppConfig.swift"
    "WatchApp/Info.plist"
    "WatchApp/Orbit.entitlements"
)

for file in "${TARGETS[@]}"; do
    if [ ! -f "$file" ]; then
        echo "Skipping (not found): $file"
        continue
    fi
    # Order matters: group ID first because it contains the bundle ID as a
    # prefix (otherwise the bundle replace would corrupt group.com.orbit.app).
    perl -i -pe "s/\Q$CANONICAL_GROUP\E/$NEW_GROUP/g" "$file"
    perl -i -pe "s/\Q$CANONICAL_BUNDLE\E/$NEW_BUNDLE/g" "$file"
    if [ -n "$NEW_TEAM" ]; then
        perl -i -pe "s/\Q$TEAM_PLACEHOLDER\E/$NEW_TEAM/g" "$file"
    fi
    echo "Patched: $file"
done

# Record current identifiers so the script can re-apply itself after a
# pull resurfaces the canonical strings.
mkdir -p Config
{
    cat <<EOF
// Identity.xcconfig — personal identifiers for this machine.
// Generated by Scripts/setup-identity.sh on $(date "+%Y-%m-%d %H:%M:%S").
// Gitignored: see .gitignore. Re-run ./Scripts/setup-identity.sh after
// any \`git pull\` that touches project.yml.

ORBIT_BUNDLE_ID = $NEW_BUNDLE
ORBIT_APP_GROUP = $NEW_GROUP
EOF
    if [ -n "$NEW_TEAM" ]; then
        echo "DEVELOPMENT_TEAM = $NEW_TEAM"
    else
        echo ""
        echo "// DEVELOPMENT_TEAM not set. Run ./Scripts/setup-identity.sh"
        echo "// <bundle> <group> <team-id> to bake it in, or edit this file."
    fi
} > "$IDENTITY_FILE"

echo ""
echo "Wrote $IDENTITY_FILE."
if [ -z "$NEW_TEAM" ]; then
    echo ""
    echo "Note: DEVELOPMENT_TEAM is unset. Xcode will keep nagging until you"
    echo "either re-run with a team id arg or add a DEVELOPMENT_TEAM = XXXX"
    echo "line to Config/Identity.xcconfig."
fi
echo ""
echo "Next: xcodegen generate"
