#!/usr/bin/env bash
# Writes Config/Identity.xcconfig with your personal bundle + App Group
# identifiers. The file is gitignored so future `git pull` never conflicts
# with your IDs.
#
# Run once per checkout (or whenever you change identifiers):
#
#   ./Scripts/setup-identity.sh com.joshgreen.orbit group.com.joshgreen.orbit
#
# After running:
#
#   xcodegen generate
#   open Orbit.xcodeproj
#   Then in Xcode set your Team on each of the three targets.

set -euo pipefail

if [ "$#" -ne 2 ]; then
    cat >&2 <<USAGE
Usage: $0 <bundle-id> <app-group-id>

Example:
  $0 com.joshgreen.orbit group.com.joshgreen.orbit

Both must be unique to you under your Apple Developer account.
USAGE
    exit 1
fi

NEW_BUNDLE="$1"
NEW_GROUP="$2"

if [[ "$NEW_GROUP" != group.* ]]; then
    echo "Error: App Group identifier must start with 'group.'" >&2
    exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$REPO_ROOT/Config/Identity.xcconfig"

cat > "$DEST" <<EOF
// Identity.xcconfig — personal identifiers for this machine.
// Generated by Scripts/setup-identity.sh on $(date "+%Y-%m-%d %H:%M:%S").
// Gitignored: see .gitignore.

ORBIT_BUNDLE_ID = $NEW_BUNDLE
ORBIT_APP_GROUP = $NEW_GROUP
EOF

echo "Wrote $DEST:"
echo "  ORBIT_BUNDLE_ID = $NEW_BUNDLE"
echo "  ORBIT_APP_GROUP = $NEW_GROUP"
echo ""
echo "Next: xcodegen generate && open Orbit.xcodeproj"
